### ISSUE TITLE
Option to remove wind noises when taking control of AI

### ISSUE THREAD

**Issue by CreepPork** [oOKexOo/AresModAchillesExpansion#100]
This can alarm some players and make them look around for the Curator and maybe in some respects ruin the _secret surprise_ that the Curator was planning. It would be great if in addon options this would be included as would satisfy most needs of other people.

_Woo! #100 issue :D_

**Comment by oOKexOo** [comment]
The task already exists in #57. I think it would be a perfect feature for the Hide Zeus module.
