### ISSUE TITLE
Possible to make change side module use the area select function?

### ISSUE THREAD

**Issue by Snak3Doc** [oOKexOo/AresModAchillesExpansion#108]
Is it possible to make the change side module use the area select function to make swapping large groups to different sides easier/quicker?

**Comment by oOKexOo** [comment]
I provided the [selection option](https://github.com/oOKexOo/AresModAchillesExpansion/wiki/Selection-Option) for this purpose. Note that the module was designed for players, not AI.
I would edit the group attributes instead. Btw. the changes will be applied to all groups you selected right before you open the attribute window.
