### ISSUE TITLE
About Garrison

### ISSUE THREAD

**Issue by DanMorera** [oOKexOo/AresModAchillesExpansion#115]
I have a problem,  after telling a group of units to garrison in a building in Zeus,  if I get out of Zeus, or leave them alone running in a server and come back the unit will leave the building and for outside, is there a way in zeus mode to garrison the troops and have them not move from their assigned place?

**Comment by CreepPork** [comment]
Hi, are you using AI modifications like VCOM AI?

**Comment by DanMorera** [comment]
Negative no ai modifications

**Comment by CreepPork** [comment]
Interesting, it should keep them in place, do you use any other mods and could you provide an .rpt file?

**Comment by DanMorera** [comment]
Mods being used:
ACE
ACEX
ARES
ASR_AI3
CBA
CUP TERRAINS
FAP
MCC
MELB
MRT
PROJECT OPFPR
RHPISTOL
RHS_AFRF3
RHS_GREF
RHSUSF3
RHSSAF
SMA
TASKFORCERADIO
TF47LAUNCHERS

Not sure how to obtain the .rpt file, what is it?

Thanks for your help

**Comment by CreepPork** [comment]
No, you are using an AI modification - ASR_AI3.

It's not a fault (_sort of_) of Achilles. As it uses different scripts to manipulate the AI it doesn't work well together with the Garrison module. The same can be observed using VCOM AI.

Remove ASR_AI3 and then try again.

**Comment by DanMorera** [comment]
Hey thanks, I'll try this and let you know how it goes in a day or two,
thanks again.

**Comment by oOKexOo** [comment]
I'm pretty sure that's the issue. Nice work @CreepPork!
