### ISSUE TITLE
AI Mechanized group shoot in all direction when suppressing

### ISSUE THREAD

**Issue by ColdEvul** [oOKexOo/AresModAchillesExpansion#14]
A Mechanized group with a couple of AI soldiers and a armed vehicle shoot in every direction when suppressing.
### Reproduce
1. Spawn a AI mechanized group place suppression target
2. Assign the target look on the utter chaos.

**Comment by oOKexOo** [comment]
I've noticed that in some cases the module leads to a chaos. But I could not yet reproduce it presistently. Maybe your example can help me to track the problem. However; I cannot guarantee there's a solution to it as wrong AI behaviour is generally a nasty thing to fix.

**Comment by oOKexOo** [comment]
This issue sould be solved in 0.0.4!
