### ISSUE TITLE
Suppressive fire module is not removable

### ISSUE THREAD

**Issue by ColdEvul** [oOKexOo/AresModAchillesExpansion#15]
`Suppressive fire` module is not removable.

### Reproduce
1. Put down a couple of `Suppressive fire` modules
2. Try to remove them,

**Comment by ColdEvul** [comment]
Apparently a random issue.

**Comment by oOKexOo** [comment]
This error occurs when the Zeus Game Master Module does not load inofficial addons. I've changed the organization of the add-on a lot for the next update (0.0.3). If all works fine, the add-on gets added automatically such that this bug will be fixed as well.

**Comment by oOKexOo** [comment]
Should be fixed in Alpha 0.0.3

**Comment by oOKexOo** [comment]
The problem is fixed by now. In any other case, please create a new issue report.

**Comment by ColdEvul** [comment]
Gold!
