### ISSUE TITLE
Adding custom modules doesn't work in postInit

### ISSUE THREAD

**Issue by Zakant** [oOKexOo/AresModAchillesExpansion#16]
Adding a custom module is not working in postInt because the module tree was not loaded at that time. This results in script erros, due `Ares_category_list` is undefined. Workaround for now is to wait a few secounds (i used ~10) befor adding the custom modules.
In long term it would be an option to "cache" calls to `Ares_fnc_RegisterCustomModule` that happend before Ares is up and just execute them afterwards. I might look into that issue myself if i got a little more time left. 

Edit: Is their any dependencie to CBA in place or planed? Their event framework would give a nice approach to that problem.

**Comment by oOKexOo** [comment]
To be honnest: I will probably remove CBA dependencies as there is only the artillery fire module that actually need a CBA function.
I completely forgot post init integrations of custom modules, but it should be an easy thing for me to fix it.

**Comment by oOKexOo** [comment]
Post init execution should work in Alpha 0.0.3

**Comment by McDiod** [comment]
Can confirm. Works now.
