### ISSUE TITLE
Script Error and Massive Client .rpt Spam

### ISSUE THREAD

**Issue by JHill29th** [oOKexOo/AresModAchillesExpansion#22]
When entering the Zeus interface the following script error spams the client .rpt.  Not a small amount of spam either; caused the client .rpt to reach well over 2 MB in size.  link to [.rpt file](https://www.dropbox.com/s/u1lzho4cnhz6bzm/arma3_2016-10-16_00-52-42.7z?dl=0)

``` sqf
1:09:20 Error in expression <= _pos distance curatorcamera;
if (_dis < _fadeEnd) then {
_coef = linearconvers>
 1:09:20   Error position: << _fadeEnd) then {
_coef = linearconvers>
 1:09:20   Error <: Type code, expected Number,Not a Number
```

**Comment by oOKexOo** [comment]
What you have reported seems to be a CBA issue.
It even happens if you run CBA alone.
Hence, you should report it to CBA team.

**Comment by JHill29th** [comment]
Oh, I hadn't tested CBA alone.  Thank you, I'll pass this to the CBA team then.

**Comment by commy2** [comment]
fixed in https://github.com/CBATeam/CBA_A3/pull/536

Can be closed here : )

**Comment by oOKexOo** [comment]
@commy2 
Thank you for the fast fix!
