### ISSUE TITLE
[Request] Setting for Auto Collapsed Unit list

### ISSUE THREAD

**Issue by john681611** [oOKexOo/AresModAchillesExpansion#26]
**Issue:**
Switching between tabs of units to spawn always causes the list to expand into a partially expanded list (overfilling the side bar)
If I'm looking for units from a faction of the lower part of the list its no fun :(
Its especially bad with RHS.

**Current Work around**
Search one character and delete it. to get a collapsed list. 

**Permission:**
I'm not experienced in Zeus modding but i can give it a shot if you don't have time just give me some pointers.

**Comment by Grezvany13** [comment]
I was thinking the same and I might have a solution for this (not tested):

```
// -- add this to config.cpp
class CfgFunctions
{
	class TAG
	{
        tag = "TAG";

        class Curator
        {
            class onLoadCurator { file = "onLoadCurator.sqf"; };
        }
}
class RscDisplayCurator
{
	onLoad = "[_this select 0] call TAG_fnc_onLoadCurator;";
};
```
```
// -- add this to fn_onLoadCurator.sqf
#include "\A3\ui_f_curator\ui\defineResinclDesign.inc"

if (!hasInterface) exitWith {};

disableSerialization;

// no idea if the correct params are used here
["onLoad", _this, "RscAttributeSide", "CuratorDisplays"] call (uinamespace getvariable "BIS_fnc_initDisplay");

_this spawn
{
    disableSerialization;
    _display = _this select 0;

    // no idea if the correct displays are selected
    // no idea if 'tvCollapse' works like this
    _tree_units = _display displayCtrl IDC_RSCDISPLAYCURATOR_MODEUNITS;
    _tree_units tvCollapse []:

    _tree_groups = _display displayCtrl IDC_RSCDISPLAYCURATOR_MODEGROUPS;
    _tree_groups tvCollapse []:
};
```

In short; 
the script will trigger the moment the Curator display is shown (press Y in game to become Zeus). It will then wait till you open the right column (which happens by default). Lastly it will try to find both the Units list and the Groups list, and collapse all the items in there.


I haven't tested the above, nor I'm I sure if the correct displays are targeted, but it should give a pointer on how to solve the issue.

**Comment by oOKexOo** [comment]
Thx Grezvany13. You got the right approach. The actual implementation in Achilles is even easier, since there is already the onModuleTreeLoad function. I will take care of it.

**Comment by oOKexOo** [comment]
Integrated in V.0.0.5.
