### ISSUE TITLE
Tripple loading Zeus interface timeouts

### ISSUE THREAD

**Issue by Arcanum417** [oOKexOo/AresModAchillesExpansion#27]
When a zeus first time loads the interface (entities on mission start, units on pressing z) it looks like it loads, unloads loads a black screen with system cursor only (freezes game) and if client has a good enough pc it iwll load zeus interface second time and it works. But for some people it will freeze game for so long, that battleye kicks them with timeout. Happens on last version. Used Alpha 0.0.3c before and worked fine (still loads zeus 2 times but without this long freeze and blackscreen)

**Comment by oOKexOo** [comment]
Basically since 0.0.3 the initialization of Achilles has become quite nasty. I had to do it that way in order to get Achilles working properly on vanilla Zeus map which would normally not allow custom client side Zeus add-ons.
I probably found a much better solution which I will introduce in 0.0.5 if it works as intended.

**Comment by Arcanum417** [comment]
And some light quick dirty fix if we use achilles with custom everything ? Addon on server and custom zeus mission. We would need to rollback, and we quite like the other added stuff in 0.0.3.

**Comment by Arcanum417** [comment]
I will just sign it myself, or if you would be so kind, sign it for me with new disposable key ?

**Comment by oOKexOo** [comment]
I will release the modified version including bikey on github by tomorrow.

**Comment by Arcanum417** [comment]
Great, it is quite unusable now, it freezes game for everyone on server when someone is opening zeus interface for the first time and for a quite long time.

**Comment by TheConen** [comment]
We have the same problem, I'd appreciate a modified version, too - we don't need Zeus on vanilla zeus missions. Is the modified version already up? I couldn't find anything under https://github.com/oOKexOo/AresModAchillesExpansion/releases

**Comment by Arcanum417** [comment]
It is a new branch, pbos also there https://github.com/oOKexOo/AresModAchillesExpansion/archive/(CED.0.0.4).zip

**Comment by TheConen** [comment]
Thanks a lot.

**Comment by Arcanum417** [comment]
@oOKexOo I tested it and people no longer complain, so I guess its safe to asume it works. Thanks for resolving this quickly.

**Comment by TheConen** [comment]
Will you provide an "init-improved" version for all releases from now on?

**Comment by oOKexOo** [comment]
@Arcanum417 
Glad to hear it worked fine. I had to do some further tests, but all seem to be fine. I made an official release which is the same version you downloaded.

@TheConen 
It's what I intend to do. I still have to figure out how to handle vanilla Zeus maps, but I'm sure I'll find a solution.

**Comment by Nels0** [comment]
Can you add detection for the vanilla Zeus maps so it only does the workaround for those specific mission files?

**Comment by oOKexOo** [comment]
My intended approach goes in a similar direction, but more general. I basically detect the modules are present in the mission which are responsible for the need of a workaround.

**Comment by oOKexOo** [comment]
Should be much better in V.0.0.5, since CED init optimization was integrated.

**Comment by Arcanum417** [comment]
Worked with CED version just fine. Now upgraded to V.0.0.5A and its back. Addon running on client and server custom mission with just Game master modules (no Game mode module present) and its still loading zeus interface quite longer and a few times. @oOKexOo

**Comment by oOKexOo** [comment]
Hm, that's odd. I have to think about a CED version for 0.0.5.

**Comment by Arcanum417** [comment]
Sorry, it looks like it is fixed now, missmatch on my side.

**Comment by oOKexOo** [comment]
Thx for the report. So we can finally close that chapter.
