### ISSUE TITLE
Stacking objects Snap-to-the-Ground

### ISSUE THREAD

**Issue by unhappytroll** [oOKexOo/AresModAchillesExpansion#28]
1. Place 1 H-barrier on top of another (in Zeus or Eden).
2. Start Zeus session.
3. If placed in Eden, add H-Barriers to Zeus.
4. Select them both and move them across terrain.
5. Top one is snaps to the ground through bottom one.

Is there any way to workaround this bug/feature? Obviously, this is game physics fault, and most probably embedded into engine, -  but may be?

**Comment by oOKexOo** [comment]
Yeah, the feature is hardcoded, that's why I introduced the concept of advanced compositions. Good for you that I intend to extend the object group/ungroup feature from advanced compositions to any object in 0.0.5. Till then, you can either use the "attach to" module or create an advanced composition.

**Comment by unhappytroll** [comment]
tbh, I do not understand how advanced compositions work now. Can't do them from inside the game.

**Comment by oOKexOo** [comment]
In your specific case I would just use the "attach to" module. 
Regarding to advanced compositions: Make sure you understand the concept of "selection option" described in the in-game field Manual. Thereafter, it shouldn't be that hard to create advanced compositions yourself. In the case you have still questions to that feature, please let me know.

**Comment by unhappytroll** [comment]
BTW, why there is no H-Barriers and sandbags in single objects list? Well, there is almost no wall objects comparing with Eden, tbh. I'll check, but I do think it was not so in Ares.

**Comment by unhappytroll** [comment]
disregard last comment, i'll have memry glitches, sorry

**Comment by unhappytroll** [comment]
Oh, that way. Ok, I'll try it, thank you.
