### ISSUE TITLE
[Feature] [PR] Mod Settings (CBA), Curator Vision Modes, Module DLC icons

### ISSUE THREAD

**Issue by Grezvany13** [oOKexOo/AresModAchillesExpansion#31]
As promised at the BIS forums ([here](https://forums.bistudio.com/topic/191113-ares-mod-achilles-expansion/?p=3118564) and [here](https://forums.bistudio.com/topic/191113-ares-mod-achilles-expansion/?p=3118757)) I've created a Pull Request with several additions to AresAchilles.

Please check the PR comment(s) of #30 for more details about the changes made and new features available.

**Comment by oOKexOo** [comment]
Thank you for the notification. I closed this ticked and will further comment in the corresponding pull request section.
