### ISSUE TITLE
[Request] Defining custom modules like normal Ares

### ISSUE THREAD

**Issue by nonsindeads** [oOKexOo/AresModAchillesExpansion#35]
Is it a way to use self programmed modules from Ares or can you implement the feature?

Look here when you don't know what i mean
https://github.com/astruyk/Ares/wiki/Extras

**Comment by oOKexOo** [comment]
Custom modules can still be implemented the same way in Achilles. 
`["My Category", "My Module", { hint "Hello World!"; }] call Ares_fnc_RegisterCustomModule; `

However, custom reinforcement pools are currently not available, since the reinforcement module has changed a lot.
