### ISSUE TITLE
Mortars on fire mission won't shot more than one shell

### ISSUE THREAD

**Issue by unhappytroll** [oOKexOo/AresModAchillesExpansion#36]
Mortars will fire only one shell with fire mission module, no matter how many you set for them to fire.

1. Place manned  Mk6 mortar turret in Zeus mode. Side color is not matter in this.
2. Place artillery target. 
3. Put Artillery Fire Mission on map, Mk6 mortar - Marker, select target and set 2 or more shots.
4. Mortar will shot only one time, no matter how many shots you selected.

This is not an issue with self-propelled artillery, it fires it's number of shots properly.
Arma  3 version - current+performance client 07.
Achilles version - 0.0.4d

**Comment by oOKexOo** [comment]
Thx for the notification. Artillery fire missions are very essential for Zeus, so fixing this issue definitely has high priority.

**Comment by unhappytroll** [comment]
np.

**Comment by oOKexOo** [comment]
I identified the problem. The script command [commandArtilleryFire](https://community.bistudio.com/wiki/commandArtilleryFire) is currently not working properly for mortars. See [T121931](https://feedback.bistudio.com/T121931).

**Comment by unhappytroll** [comment]
oh well, BI as usual

**Comment by oOKexOo** [comment]
Should be fixed in V.0.0.5
