### ISSUE TITLE
Advanced AI Attributes not applying on non-local units

### ISSUE THREAD

**Issue by Nels0** [oOKexOo/AresModAchillesExpansion#38]
On dedicated server - 40man operation.
ACE, TFAR, CBA, RHS, other minor mods.
Advanced attributes like fire mode when accessed per group (I.e group fire mode) will not stick when set except on units that have been transferred to Zeus or spawned by Zeus. Setting the attributes on a waypoint appears to work.

**Comment by oOKexOo** [comment]
Yup, they are currently only working on local units.

**Comment by oOKexOo** [comment]
Should be fixed in V.0.0.5
