### ISSUE TITLE
Ares_fnc_RegisterCustomModule not working

### ISSUE THREAD

**Issue by McDiod** [oOKexOo/AresModAchillesExpansion#39]
**Arma 3 Version:** `1.6.6`
**CBA Version:** `3.1.2`
**Achilles Version:** `CED - Alpha 0.0.4d`

**Mods:**
- `@CBA_A3`
- `@Ares`

**Description:**
* this is different from #16 
* sometimes it does nothing
* sometimes it creates an empty category

**Tested with:**
* dedicated & local host
* #adminLogged & variable name as zeus owner
* virtual & physical zeus units
* zeus interface open & zeus interface closed
* preInit, postInit, running game

**Comment by oOKexOo** [comment]
I could reproduce your issue. The new init handling introduced in CED leads to an issue in `Ares_fnc_RegisterCustomModule `. In contrast, the function works fine in the normal V.0.0.4d.
I try to get it right in V.0.0.5 such that both `Ares_fnc_RegisterCustomModule ` and the new init handling work.

**Comment by oOKexOo** [comment]
Should be fixed in V.0.0.5
