### ISSUE TITLE
Submarine Object is flipped 180°

### ISSUE THREAD

**Issue by Chronophylos** [oOKexOo/AresModAchillesExpansion#45]
The Submarine Object is flipped 180°.

**Comment by oOKexOo** [comment]
What do you mean with flipped 180°?
The script just spawns it the way BIS designed the model.

**Comment by Chronophylos** [comment]
When turning the submarine in the Zeus interface it faces the wrong direction.

**Comment by oOKexOo** [comment]
I see now what you mean, but this issue is related to the submarine object and not to Zeus. BIS must have messed up the direction.
