### ISSUE TITLE
Server de-synchronization and connectivity issues

### ISSUE THREAD

**Issue by UGDev-Mokka** [oOKexOo/AresModAchillesExpansion#47]
Hello there,

on our public Arma server we run Zeus missions on a regular basis. In order to enable having a proper and unique mission (almost) every night, quite a few members of our community have been fitted with access to a Zeus curator module (~18).
Ever since the update from 0.0.4d to 0.0.5, we have had massive connectivity issues on the server. The server itself locks up, Arma will become unresponsive and can only be closed by directly killing off the process in the task manager. Players will lose connection while playing, and all players JIP will be kicked.

We are quite sure, that this has to do with the recent update. After downgrading versions from 0.0.5 to 0.0.4d, all issues have vanished. I believe. that it might have something to do with the new initialization on Achilles' side.
I will also try and get my hands on rpt dumps both client and server-side, in order have a bit of clarity.

Thanks for taking the time to read this, I look forward to hearing from you soon!

**Comment by oOKexOo** [comment]
With version 0.0.5 you have two ways to improve initialization:
1) Load the add-on to the server.
2) Set “Default Addons” to “All Addons (including unofficial ones)” for the curator module in your mission in Eden editor.

As I assume you are running the vanilla game master maps, I recommend trying the first approach.
If you still get issues, please send me the RPTs.

**Comment by UGDev-Mokka** [comment]
Thank-you for the quick response. We will try loading the addon with the server in the next days. Also still trying to fetch a few rpt logs.

**Comment by oOKexOo** [comment]
Probably outdated. If this issue is still not solved, please open a new ticket.
