### ISSUE TITLE
(unwanted) dependency of Achilles on missions build while mod is enabled

### ISSUE THREAD

**Issue by Grezvany13** [oOKexOo/AresModAchillesExpansion#48]
As reported several times at the BIS forums; Achilles adds a mod dependency in missions when created/modified in Eden while the Achilles mod was enabled.

I've been able to backtrack the issue to the following config file: [data_f_achilles/config.cpp](https://github.com/oOKexOo/AresModAchillesExpansion/blob/master/%40AresModAchillesExpansion/addons/data_f_achilles/config.cpp)

It seems that overwriting these items (adding `scopeCurator = 2;`) makes them part of the addon and therefor makes it a dependency of the mission.
However, since it includes the H-Barriers and Sandbags, this will mean that probably 90% of all missions created with Achilles enabled will have this dependency.

If I'm correct all those items currently have `scopeCurator = 2;` by default, and can be removed from the addon.

**Comment by BryanBoru** [comment]
the few times I've had this happen, I was able to delete the achilles references in the dependencies section of the mission.sqf and then reload the mission without issue. I haven't extensively tested this theory out though, because it was minor edits and smaller additions I was making to missions and not complete builds. I would just suggest not having it loaded during editing as it is more meant to be a zeus mod and not 3den mod.

**Comment by Grezvany13** [comment]
@BryanBoru Your theory is correct, and I did test removing the dependency from the mission file and didn't get any issues loading the mission afterwards.

It's not a hard dependency for objects which only exist in Achilles, but existing (vanilla) objects which are redefined.

Luckily it's not a major bug and just a small annoyance, but I'm sure a lot of people would like to see this fixed.

**Comment by oOKexOo** [comment]
It seems that there are still leftovers from earlier test. I better should have done them in a separate dev branch.
As far as I know, the objects defined there are not available for Zeus in the empty object category. In fact they also have `scopeCurator = 1;`. However, I wasn't able to recover them yet. I need to do more investigations. Furthermore, I have to check how to prevent those objects from being dependent on the add-on.

**Comment by oOKexOo** [comment]
Should be resolved in 0.0.6
