### ISSUE TITLE
Weapon crates placement errors

### ISSUE THREAD

**Issue by unhappytroll** [oOKexOo/AresModAchillesExpansion#49]
1. Some errors in placing weapons crates from Arsenal tab:
 - instead of Guerrilla weapons crate there is NATO weapons crate creates;
- crates placed with random(?) displacement from point of placing;
- if they placed on a floor of buildings, there big chance of them to mess up and explode.

Video proofs: https://youtu.be/_9TCBtze_Co

**Comment by oOKexOo** [comment]
I will try to improve the spawn position.
