### ISSUE TITLE
Addon Not Working

### ISSUE THREAD

**Issue by MMDPS20** [oOKexOo/AresModAchillesExpansion#5]
Wheni have load the addon (the game and launcher says is has load sucessfull) nothing of the addon(zeus modules,etc) is in the zeus (modules) just vanila and my MCC modules are there

**Comment by oOKexOo** [comment]
Thank you for posting here. As I cannot reproduce the error, I need some more informations:
1) Do you see the red helmet icon in the bottom in the main menu? (if not: you likely did not installed the add-on properly)
2) In the ArmA 3 Launcher go to PARAMETERS > ADVANCED (tab) > AUTHOR (+)
Set a tick for "Show Script Errors"
3) With the settings from 2), do you get any script error warnings?
4) Which verison of MCC do you have? (the newest from steam workshop or an older from Armaholic?)

**Comment by oOKexOo** [comment]
If this issue is still there, please post a new topic with more details.
