### ISSUE TITLE
Zeus missing almost all factions

### ISSUE THREAD

**Issue by JeroenKok** [oOKexOo/AresModAchillesExpansion#52]
1) When entering Zeus, the UI is normal but after a few seconds fades to black and then all factions are missing besides NATO and Syndicat.
2) CBA_A3 v3.1.2.161105, Ares - Achilles Expansion a0.0.5
3) English
4) Editor, when going into previous
5) Always
6) Enter Editor. Place character - player - place game master module and sync to player. Enter preview and press y and wait.
7) No script error was displayed

**Comment by oOKexOo** [comment]
Can you check, whether the other factions are actually listed as available?

How to:
1) When you are Zeus, go to the escape menu.
2) Options > Game > Configure Addons (button at bottom) > Achilles – Available factions (Combo box choice)
3) Make sure that all factions are checked.

Note: This option is a new feature introduced in 0.0.5, which helps to manage factions.

**Comment by KagenoOkami** [comment]
Okay, so that's where they went.
That did the trick.

I recall that menu from a few days ago and thought it was from ALIVE

Thanks.
