### ISSUE TITLE
FadeMusic

### ISSUE THREAD

**Issue by tacplay** [oOKexOo/AresModAchillesExpansion#55]
FadeMusic doesn't work with Ares enabled.

**Test**
Make a trigger
- anybody
- OnActivation: 5 fadeMusic 1; playMusic "LeadTrack05_F_EPC"; 
- onDeactivation: 5 fadeMusic 0;

**Vanilla**: all is fine, you walk in, music starts, you walk out, music ends after 5 sec. fading
**Ares**: You walk in, music starts, you walk out, music plays until the track is done, full volume

**Comment by oOKexOo** [comment]
Please make sure that it is not an ACE3 instead.

**Comment by tacplay** [comment]
Hmm, you're right. It's ACE.
Sorry. Should test with vanilla bevor I post an issue.

Can be closed.
