### ISSUE TITLE
Can not spawn in templates

### ISSUE THREAD

**Issue by railgame1** [oOKexOo/AresModAchillesExpansion#59]
1) Can not spawn in templates
2) Achilles (0.0.6c), CBA_3 (3.2.1)
3) English
4) client on hosted server
5) always
6) In game as zeus, head to the groups section --> Templates --> Try place one down
7) On the 1.68 game version, 64-bit,

**Comment by oOKexOo** [comment]
Yeah, this issue was reported several times and can also be observed for other add-ons like ZEC as well.

**Comment by railgame1** [comment]
Ok, thanks. I also assume you know the button for damaging certain parts of a vehicle is gone? (e.g. the tailrotor of a heli)

**Comment by oOKexOo** [comment]
Yup, this is also part of the upcomming hotfix.

**Comment by oOKexOo** [comment]
Both are fixed.
