### ISSUE TITLE
Disabling object animation;

### ISSUE THREAD

**Issue by Kriegsler** [oOKexOo/AresModAchillesExpansion#7]
Default Ares had a "disable animation" module,that just froze objects/NPCs. the Achilles expansion removes this function. 

*(in-game example)* You can't place a laptop on a table. It's will go through. If you disable the animation/movement/freeze it it's won't.

**Comment by oOKexOo** [comment]
The disable simulation functionality is definitely essential. It somehow got lost.

**Comment by Kriegsler** [comment]
Thank you for taking your time to answer it! I hope the next update will come soon.
