### ISSUE TITLE
Feature Request: MCC Style custom IED objects

### ISSUE THREAD

**Issue by Snak3Doc** [oOKexOo/AresModAchillesExpansion#70]
MCC had an amazing feature for IED's  (doesn't work with multiple Zeus so it's useless for multi Zeus missions)

When the IED module was placed it opens a dialogue with with options to choose 
-object ( water barrels, suitcases, cars (and wrecks) ect)
-explosive type (different size explosives)
-direction (none, north, south, east, west)
-trigger type (faction present in x metres trigger and remote triggerman (spawns unit of choice with ace or scroll wheel action  to detonate charge or option to manually arm it through ace when walking up to it in RC of ai

Preferably these would all be affected by ace explosives (extra bang) and they would then be defuseable through ace as well

**Comment by CreepPork** [comment]
@Snak3Doc I don't want to rush ahead, but I'm currently rewriting MCC IED modules.

**Comment by Snak3Doc** [comment]
If you can incorporate with Achilles or work with it standalone from MCC that would be great, MCC is good and all but for milsim Zeus ops with 4 or more zeus it A) doesn't​ the work with multiple zeus's and B) to be honest between Achilles and experience you can make better missions without MCC it's slow and clunky and has heaps of useless stuff a milsim group with good zeus's don't need.

**Comment by CreepPork** [comment]
@Snak3Doc It's some time away from completion, but some parts of the code could be incorporated but some are dependent on audio and I don't want to create a dependency for all players using Achilles, so I'll probably leave that in my own "expansion".

**Comment by oOKexOo** [comment]
As your code is based on MCC, it would probably be better to pull your improvements there I guess.

**Comment by CreepPork** [comment]
@oOKexOo But it's fully standalone and doesn't require MCC. And by the looks of things shay_gman isn't pushing any updates.

**Comment by oOKexOo** [comment]
@CreepPork
At the end of the day, it is your call whether and how you want to publish that module. As you correctly stated it does not fit to Achilles due to the inclusion of sound files. Well, except you would make a lite version.

**Comment by CreepPork** [comment]
@oOKexOo Yeah, I suppose.

**Comment by Snak3Doc** [comment]
I'm probably missing something but why do sound files effect making it work alongside Achilles

**Comment by CreepPork** [comment]
@Snak3Doc As Achilles has been designed for no requirment for the players, only required by Zeus and Kex wanting to keep it like that (as do I), only partialy some modules could be implemented. Something like Suicide Bombers couldn't be implemented without removing the sounds for it, as such removing the audio dependency that is for the players.

**Comment by Snak3Doc** [comment]
Fair enough, though every group I've seen just has clients running it anyway for simplicity, would it maybe be possible to have a light version in Achilles with just the IED's and not the suicide bomber? (i know this isnt just for milsim but if your running ace and tfr you have all the tools for doing suicide bombers anyway)

**Comment by CreepPork** [comment]
Introduced in #86 pull request.
