### ISSUE TITLE
NATO and CSAT units other than Pacific kind disappiared from unit menu

### ISSUE THREAD

**Issue by unhappytroll** [oOKexOo/AresModAchillesExpansion#71]
Subj. No other mods loaded other than CBA and 3den Enhanced, so it is obvious misconfiguration in last patch.

**Comment by unhappytroll** [comment]
sorry for misspelling

**Comment by oOKexOo** [comment]
All seems to be fine for me (tried with Achilles + CBA only with the official game master mission on a dedicated server).
Please make sure that you did not deactivate those factions ba accident.
Options > Addon Options > Achilles - Available factions (combo box)

**Comment by CreepPork** [comment]
@oOKexOo Working fine for me too!

**Comment by unhappytroll** [comment]
nope, everything activated. 

ok, test run. mods: 3den Enchanced, CBA_A3, Achilles, ZEC, DXX compositions, ShackTacUI.
https://youtu.be/_TaWP0BfVN4
I can stream it if you want to check this issue online ^)

**Comment by oOKexOo** [comment]
Thx, for your effort. I just tried to reproduce your video step by step. I even ordered the add-ons the same way (the order does matter in the case two add-ons override the same class). Nevertheless, I still did not observe your issue...
In your case it seems that the two factions get filtered, but I don't know why.

BTW: The combo box issue is a known vanilla issue. Minimizing the "System: Init" tab is a possible workaround.

**Comment by unhappytroll** [comment]
ok, I falled back to 0.0.6d and x32 client - issue is still present.  
I will close it, because looks like this is Arma fault, but hell if I know what is the problem.

**Comment by unhappytroll** [comment]
But most strange is that original Ares still works fine.
The only thing left to check - is this a last performance client bug. if not - well... I'm out of ideas.

**Comment by unhappytroll** [comment]
no, it's not, original March build of 1.68 has same issue, even with 0.0.6d. So something is broke in Arma installation I will try to reinstall then. ^(
by the way, why Zeus interface gets redrawn after loading?

**Comment by unhappytroll** [comment]
fully reinstalle

**Comment by unhappytroll** [comment]
Fully reinstalled Arma from scratch. No help, same issue. After interface reinitialization to red panel.

**Comment by oOKexOo** [comment]
Sry, I didn't mean to give up right there. I just needed some time to think about that issue once more.
Your latest report actually support my fear that your Achilles faction filter variable is broken for some reasons.

So here is what I suggest to try:
1) Go to parameters in your ArmA 3 launcher and check "Show Script Errors".
2) Launch ArmA and start your sample zeus mission again.
3) Go to Options > Addon Options > Achilles - Available factions (combo box)
4) Uncheck NATO, CSAT and NATO (Pacific). (You should observe that the interface is reloaded and NATO (Pacific) should also disappear)
5) If all went fine, go back to the settings and enable all factions again.

In the case you observe script errors during the procedure,  make screenshots of them.
I hope with this procedure the faction variable can be fixed. If this is not the case, we'll check and fix the variable with a small script. Just let me know.

**Comment by unhappytroll** [comment]
Case closed. After reinstall it actually shows that filter is engaged for some reason - it was not showing it before reinstall. But I will try that you suggest right now fgj.

**Comment by unhappytroll** [comment]
Tried it, works without any errors. Now why this option dialog wasn't showing filter changes... but that's Arma.
