### ISSUE TITLE
[Feature Request] Dynamic loadout

### ISSUE THREAD

**Issue by unhappytroll** [oOKexOo/AresModAchillesExpansion#76]
Well, obvious question: because we have new DLC with ability to edit loadouts for aircrafts, can it be done on the fly?

**Comment by JANXOL** [comment]
Maybe I should open another feature request, but I guess I will try to add something in here, as it is also Jets DLC related:
1. Would it be possible to add aircraft carrier to zeus interface?
2. Would it be possible to add modules to manage data link on the fly?

**Comment by CreepPork** [comment]
@JANXOL Answer to your first question, it probably is not possible as it consists of multiple parts and would look very weird when you move it in game. You'll see what I'm talking about, if you place down the Carrier in Eden and then add it to Zeus using the module. And if you move the parts it will glitch out.

**Comment by oOKexOo** [comment]
I stated earlier that I intend to implement the dynamic loadout feature for the unassigned "ammo" button in the vehicle attirbutes.
