### ISSUE TITLE
Vehicle respawn is broken

### ISSUE THREAD

**Issue by CreepPork** [oOKexOo/AresModAchillesExpansion#78]
When selecting a vehicle and opening its menu (double clicking) and pressing OK, it displays an error. The following error:
![cfb0385df1ac22c4b06e338b1ac86cd3](https://cloud.githubusercontent.com/assets/1590711/26276846/be1ef25e-3d88-11e7-8eda-84c1ed9e965a.png)

**Comment by oOKexOo** [comment]
Lol, the issue does even happen in vanilla Zeus.
