### ISSUE TITLE
Update 1.70 broke CAS modules

### ISSUE THREAD

**Issue by oOKexOo** [oOKexOo/AresModAchillesExpansion#79]
Several vanilla planes are missing or do not work properly (especially for the bomb strike one).
Edit: Probably caused by the dynamic lodaout feature.

**Comment by Drofseh** [comment]
A bunch of class names for aircraft have changed, here are the planes:

B_Plane_CAS_01_F  - - ->   B_Plane_CAS_01_dynamicLoadout_F
O_Plane_CAS_02_F  - - ->   O_Plane_CAS_02_dynamicLoadout_F
I_Plane_Fighter_03_F  - - ->   I_Plane_Fighter_03_dynamicLoadout_F

There are also these brand new ones from Jets DLC:

B_Plane_Fighter_01_F
B_Plane_Fighter_01_Stealth_F
O_Plane_Fighter_02_F
O_Plane_Fighter_02_Stealth_F
I_Plane_Fighter_04_F

**Comment by oOKexOo** [comment]
Thx for the hint, but it's a bit more complicated than this. Changes in names do not matter, since my implementation iterates over any plane class in cfgVehicles.

**Comment by Drofseh** [comment]
Well I tried. ARMA's never that easy though.
