### ISSUE TITLE
Earthquake module - destroy buildings option text is missing

### ISSUE THREAD

**Issue by CreepPork** [oOKexOo/AresModAchillesExpansion#80]
When placing down the earthquake module, the module has the third parameter missing.

**Comment by oOKexOo** [comment]
I will try to reproduce it.

**Comment by CreepPork** [comment]
@oOKexOo To clarify the text to the side is missing, indicating what it does. The option works fine.

**Comment by CreepPork** [comment]
Fixed in #83 pull request,
