### ISSUE TITLE
Edit cargo not working w/error

### ISSUE THREAD

**Issue by Snak3Doc** [oOKexOo/AresModAchillesExpansion#82]
When trying to edit the cargo of supply crates ect its only seems to work sometimes, you can open the interface but you can't increase the amounts of any items, i managed to find the error, its the how full the box is bar that's causing the issue temp fix was to remove the entire bar from the gui.

File achilles\ui_f\scripts\RscAttributeInventory.sqf, line 311
Error in expression <ressposition _ctrlLoad + (_value max 0) * _coef / RscAttributeInventory_Capacity>
Error position: <* _coef / RscAttributeInventory_Capacity>

Error *: Type String, expected Number,Not a Number

**Comment by oOKexOo** [comment]
Do you know which 3rd party add-on causes this issue? (I assume it is one as I haven't observe that issue yet)

**Comment by Snak3Doc** [comment]
Ahh I can give it a go, it's rather a large modset through not sure if I'll be able to find the conflict, would it most likely be something else with a custom inventory size GUI?

**Comment by Snak3Doc** [comment]
Ill still look into if its another mod causing the issue but we think (testing will update) we got around it by adding the supply crate to zeus on mission load rather than during it with the module

**Comment by oOKexOo** [comment]
Just let me know if you determined the mod.
