### ISSUE TITLE
Function error when opening hint appears

### ISSUE THREAD

**Issue by CreepPork** [oOKexOo/AresModAchillesExpansion#84]
The error doesn't appear when the Zeus is on a dedicated server but appears either in single player or self hosted game.

Error looks like this:
![c8e71e35ad92a4a68c017ad7f419fd5d](https://cloud.githubusercontent.com/assets/1590711/26547304/05441552-4477-11e7-87e5-b069465504fa.png)

**Comment by oOKexOo** [comment]
It's merely a warning from that particular function rather than a script error, but I will check it out.

**Comment by oOKexOo** [comment]
It seems to be that the warning is caused by bis_fnc_advhint itself.
