### ISSUE TITLE
Briefing editor is a bit shifted (some buttons)

### ISSUE THREAD

**Issue by shukari** [oOKexOo/AresModAchillesExpansion#89]
right side
1920x1080 - gui scale small

PIC: https://steamuserimages-a.akamaihd.net/ugc/772778501264062257/60C01BC45AE643EE1371D089E76C410E3867DB0F/

**Comment by CreepPork** [comment]
@shukari looking more and more, you sure you posted it in the correct GitHub page? :D

**Comment by shukari** [comment]
^^ wrong mod for report... i was brain afk sry...
