### ISSUE TITLE
Factions configuration

### ISSUE THREAD

**Issue by neilzar** [oOKexOo/AresModAchillesExpansion#96]
Someone told me about the option to remove units from the faction tree, but for some reason I have no option to configure factions in the addon options. In the dropdown of configure addons I only have the curators interface and modules interface options.

I did see that the script for the factions menu is in the settings pbo, but don't know why it is not showing up ingame.

Other mods:
All 3CB BAF mods
ACE
Alive
Backpackonchest
CUP Terrains
Burnes challenger 2
LAV-25
F/A-18 super hornet
NiArsenal
Project OPFOR
RHS AFRF, GREF, USAF
STUI
TFR
USM mod

**Comment by oOKexOo** [comment]
It has been temporarly removed (see latest [change log](https://github.com/oOKexOo/AresModAchillesExpansion/blob/(0.08)/%40AresModAchillesExpansion/changelog.md))

**Comment by neilzar** [comment]
Which point in the change log is it exactly? Can't seem to find it.

**Comment by oOKexOo** [comment]
You are right. It is missing! Thx for the hint. I'll mention it in the upcomming hotfix instead.

**Comment by oOKexOo** [comment]
Mentioned in 0.0.8c
